### ISSUE TITLE
Missing config file and weights for modelnet40

### ISSUE THREAD

**Issue by wsunid** [CVLAB-Unibo/compass#1]
Hi,

Thanks for the great effort in releasing the code!

I am wondering if you will release the config file and weight for modelnet40. I saw the link to the weight of modelnet40 is broken. And I didn't find the config file in `config` folder.

Thanks!
Weiwei.

**Comment by rspezialetti** [comment]
Hi,

Thanks for reporting the problem. We will upload the missing files within a few days.

Riccardo

**Comment by rspezialetti** [comment]
Hi Weiwei,

we fixed the link with the weights for ModelNet40 and updated the config file as well.
Thanks again for your interest in our work.

Riccardo
